# Generated by Django 2.2.9 on 2020-08-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200824_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузка изображения. Опционально.', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
