# Generated by Django 2.2.9 on 2020-08-24 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Содержимое комментария. Обязательно к заполнению.', verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата комментария. По-умолчанию выставляется текущее время.', verbose_name='Дата комментария')),
                ('author', models.ForeignKey(help_text='Автор комментария. Заполняется автоматически.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
